EVENT_TYPE_LIST = ['course', 'consultation', 'lecture', 'show', 'talk', 'workshop', 'others']
EVENT_FREQ_LIST = ['Once', 'Multiple','Fexible']


ORG_TYPE_LIST = ['Association', 'Center', 'Club', 'Community', 'Company', 'Cooperative/Collective',
           'Government/Town Council/Village', 'Individual', 'Institute', 'Museum', 'NGO/Foundation',
           'Park', 'Political Party', 'School/Nursery/Kindergarten', 'Social Enterprise', 'Society',
           'Station & Network', 'Support Group', 'Union', 'University']

EXPERTISE_LIST = ['Accounting & Auditing', 'Admin & Clerical', 'Automotive', 'Banking', 'Biotech', 'Broadcast',
                  'Business Development', 'Construction', 'Consultant', 'Customer Service', 'Design', 'Distribution',
                  'Education', 'Engineering', 'Entry Level', 'Executive', 'Facilities', 'Finance', 'Franchise',
                  'General Business', 'General Labor', 'Government', 'Grocery', 'Health Care', 'Hospitality',
                  'Hotel', 'Human Resources', 'Information Technology', 'Installation', 'Insurance', 'Inventory',
                  'Journalism', 'Journalism', 'Legal', 'Legal Admin', 'Maint', 'Management', 'Manufacturing',
                  'Marketing', 'Media', 'New Grad', 'Newspaper', 'Nonprofit', 'Nurse', 'Other', 'Pharmaceutical',
                  'Planning', 'Procurement', 'Professional Services', 'Purchasing', 'QA', 'Quality Control',
                  'Real Estate', 'Repair', 'Research', 'Restaurant - Food Service', 'Retail', 'Sales', 'Science',
                  'Shipping', 'Skilled Labor', 'Social Services', 'Strategy', 'Supply Chain', 'Teaching',
                  'Telecommunications', 'Trades', 'Training', 'Transportation', 'Warehouse']

TOPIC_LINK = "https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Lists_of_topics"

# in total 222 countries
DESTINATION_LIST = ['AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AO', 'AR', 'AS', 'AT', 'AU', 'AW', 'AZ', 'BA',
           'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BM', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW',
           'BY', 'BZ', 'CA', 'CD', 'CF', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN', 'CO', 'CR', 'CU',
           'CV', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ER', 'ES', 'ET',
           'FI', 'FJ', 'FK', 'FM', 'FO', 'FR', 'GA', 'GB', 'GD', 'GE', 'GF', 'GH', 'GI', 'GL', 'GM',
           'GN', 'GP', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL',
           'IN', 'IO', 'IQ', 'IR', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN',
           'KP', 'KR', 'KW', 'KY', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV',
           'LY', 'MA', 'MC', 'MD', 'MF', 'MG', 'MH', 'MK', 'ML', 'MM', 'MN', 'MO', 'MQ', 'MR', 'MS',
           'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NC', 'NE', 'NF', 'NG', 'NI', 'NL', 'NO',
           'NP', 'NR', 'NU', 'NZ', 'OM', 'PA', 'PE', 'PF', 'PG', 'PH', 'PK', 'PL', 'PM', 'PN', 'PR',
           'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE', 'SG',
           'SH', 'SI', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'ST', 'SV', 'SY', 'SZ', 'TD', 'TG', 'TH',
           'TJ', 'TK', 'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TV', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ',
           'VA', 'VC', 'VE', 'VI', 'VN', 'VU', 'WS', 'YE', 'YT', 'ZA', 'ZM', 'ZW']

LANG_LIST = ['Abkhaz', 'Afar', 'African', 'Afrikaans', 'Akan', 'Albanian', 'Alemannic', 'Alsatian', 'Amerindian',
             'Amerindian dialects', 'Amharic', 'Angaur', 'Arabic', 'Aramaic', 'Armenian', 'Asian', 'Assamese',
             'Assyrian', 'Aymara', 'Azerbaijani', 'Azeri', 'Bahasa', 'Bahasa Indonesia', 'Balinese', 'Balochi',
             'Baluchi', 'Bambara', 'Bandjabi', 'Bangla', 'Bantu', 'Bapounou/Eschira', 'Barbuda', 'Bari', 'Basque',
             'Belorussian/White Russian', 'Bemba', 'Bengali', 'Berber', 'Bhojpuri', 'Bhotes', 'Bicol', 'Bislama',
             'Bojpoori', 'Bokmål Norwegian', 'Bosnian', 'Brahui', 'Brazilero', 'Breton', 'Bubi', 'Bulgarian', 'Burmese',
             'Burushaski', 'Cakchiquel', 'Cantonese', 'Carib', 'Carolinian', 'Castilian', 'Catalan', 'Catalán',
             'Cebuano', 'Chichewa', 'Chilomwe', 'Chinese', 'Chinyanja', 'Chisena', 'Chitonga', 'Chitumbuka',
             'Chiyao', 'Chukese', 'Circassian', 'Cisena', 'Corsican', 'Creole', 'Criolo', 'Criuolo', 'Croatian',
             'Cushitic', 'Czech', 'Dagomba', 'Danish', 'Dari', 'Dimli', 'Dinka', 'Dioula', 'Djerma', 'Dutch',
             'Dutch/Flemish', 'Dzongkha', 'Echuwabo', 'Elomwe', 'Emakhuwa', 'English', 'Estonian', 'Ewe', 'Ewé',
             'Fang', 'Faroese', 'Farsi', 'Fijian', 'Filipino', 'Finnish', 'Flemish', 'Fon', 'Foochow', 'French',
             'French patois', 'Frisian', 'Fula', 'Fulani', 'Fuzhou', 'Ga', 'Gaelic', 'Gagauz', 'Galician', 'Galole',
             'Gan', 'Ganda', 'Garifuna', 'Georgian', 'German', 'Greek', 'Greenlandic', 'Guaragigna', 'Guaraní', 'Gujarati',
             'Hainan', 'Haitian', 'Hakka', 'Hassaniya Arabic', 'Hausa', 'Hebrew', 'Herero', 'Hiligaynon', 'Hindi',
             'Hindi/Urdu', 'Hindko', 'Hindustani', 'Hiri Motu', 'Hokkien', 'Hokkien-Taiwanese', 'Hungarian',
             'I-Kiribati', 'Iban', 'Ibo', 'Icelandic', 'Ilocano', 'Ilonggo', 'Indian', 'Indonesia', 'Inuit',
             'Irish', 'IsiXhosa', 'IsiZulu', 'Italian', 'Jamaican', 'Japanese', 'Javanese', 'Jola', 'Kabardian',
             'Kabyé', 'Kadazan', 'Kalanga', 'Kannada', 'Kaonda', 'Kapingamarangi', 'Kashmiri', 'Kazak', 'Kekchi',
             'Kemak', 'Khmer', 'Kikongo', 'Kinyarwanda', 'Kiribati', 'Kirundi', 'Kiswahili', 'Korean', 'Kosrean',
             'Krio', 'Kunama', 'Kurdish', 'Kyrgyz', 'Lao', 'Latin', 'Latvian', 'Lingala', 'Lithuanian', 'Lozi', 'Luganda',
             'Lunda', 'Luri', 'Luvale', 'Luxermbourgish', 'Macedonian', 'Maithali', 'Malagasy', 'Malay', 'Malayalam',
             'Malayo-Polynesian', 'Maldivian Dhivehi', 'Malinké', 'Maltese', 'Mam', 'Mambae', 'Mandarin', 'Mandinka',
             'Maori', 'Marathi', 'Marshallese', 'Mayan', 'Melanesian', 'Melayu', 'Mende', 'Min', 'Mina', 'Minbei',
             'Minnan', 'Mirandese', 'Moldovan', 'Mon-Khmer', 'Mongolian', 'Monokutuba', 'Montenegrin',
             'Monégasque', 'Moroccan Arabic', 'Moshi-Dagomba', 'Mozambican', 'Myene', 'Nahua', 'Nahuatl', 'Nama',
             'Nauruan', 'Ndebele/Sindebele', 'Nepalese', 'Nepali', 'Niger-Congo', 'Nilo-Hamitic', 'Nilo-Saharan', 'Nilotic',
             'Nordic', 'Nubian', 'Nuer', 'Nui', 'Nukuoro', 'Nyanja', 'Nynorsk Norwegian', 'Nzebi', 'Oriya', 'Orominga',
             'Oshivambo', 'Palauan', 'Pampango', 'Pangasinense', 'Panjabi', 'Pashtu', 'Persian', 'Pohnpeian', 'Polish',
             'Portuguese', 'Portunol', 'Provençal', 'Pulaar', 'Punjabi', 'Quechua', 'Quiche', 'Quéchua', 'Roma', 'Romanian',
             'Romansch', 'Russian', 'Sami', 'Sami-Lapp', 'Samoan', 'Sangho', 'Sanskrit', 'Sara', 'Scots Gaelic',
             'Sekgalagadi', 'Sepedi', 'Serbian', 'Serbo-Croatian', 'Seselwa Creole', 'Sesotho', 'Setswana', 'Shanghaiese',
             'Shikomoro', 'Shilluk', 'Shona', 'Siamese', 'Sindhi', 'Sinhala', 'Siraiki', 'Siswati', 'Slovak', 'Slovene',
             'Slovenian', 'Somali', 'Soninke', 'Sonsoralese', 'Spanish', 'Sudanic', 'Surinamese', 'Susu', 'Swahili',
             'Swahili/Arabic', 'Swedish', 'Ta Bedawie', 'Tagalog', 'Taiwanese', 'Tajik', 'Tamang', 'Tamil', 'Telugu',
             'Temne', 'Teochew', 'Tetum', 'Thai', 'Tharu', 'Tibetan', 'Tigre', 'Tigrigna', 'Tigrinya', 'Tobi', 'Tok Pisin',
             'Tonga', 'Tongan', 'Tosk', 'Tshiluba', 'Turkic', 'Turkish', 'Turkmen', 'Tuvaluan', 'Ukrainian', 'Ulithian',
             'Urdu', 'Uzbek', 'Vietnamese', 'Waray', 'Welsh', 'Woleaian', 'Wolof', 'Wu', 'Xhosa', 'Xiang', 'Xichangana',
             'Xinca', 'Xitsonga', 'Yapase', 'Yezidi', 'Yoruba', 'Yue', 'Zande', 'Zulu']

LANG_Country = {'Afghanistan': ['Dari', 'Persian', 'Pashtu', 'Turkic'],
 'Albania': ['Albanian', 'Tosk', 'Greek'],
 'Algeria': ['Arabic', 'French', 'Berber'],
 'Andorra': ['Catalán', 'French', 'Castilian', 'Portuguese'],
 'Angola': ['Portuguese', 'Bantu', 'African'],
 'Antigua': ['Barbuda', 'English'],
 'Argentina': ['Spanish', 'English', 'Italian', 'German', 'French'],
 'Armenia': ['Armenian', 'Yezidi', 'Russian'],
 'Australia': ['English'],
 'Austria': ['German', 'Slovene', 'Croatian', 'Hungarian'],
 'Azerbaijan': ['Azerbaijani', 'Turkic', 'Russian', 'Armenian'],
 'Bahamas': ['English', 'Creole', 'Haitian'],
 'Bahrain': ['Arabic', 'English', 'Farsi', 'Urdu'],
 'Bangladesh': ['Bangla', 'English'],
 'Barbados': ['English'],
 'Belarus': ['Belorussian/White Russian', 'Russian'],
 'Belgium': ['Dutch/Flemish', 'French', 'German'],
 'Belize': ['English', 'Spanish', 'Mayan', 'Garifuna', 'Carib', 'Creole'],
 'Benin': ['French', 'Fon', 'Yoruba'],
 'Bhutan': ['Dzongkha', 'Tibetan', 'Bhotes', 'Nepalese', 'Nepalese'],
 'Bolivia': ['Spanish', 'Quechua', 'Aymara'],
 'Bosnia and Herzegovina': [ 'Bosnian', 'Croatian', 'Serbian'],
 'Botswana': ['English', 'Setswana', 'Kalanga', 'Sekgalagadi'],
 'Brazil': ['Portuguese', 'Spanish', 'English', 'French'],
 'Brunei': ['Malay', 'English', 'Chinese'],
 'Bulgaria': ['Bulgarian', 'Turkish', 'Roma'],
 'Burkina Faso': ['French', 'African', 'Sudanic'],
 'Burundi': ['Kirundi', 'French', 'Swahili'],
 'Cambodia': ['Khmer', 'French', 'English'],
 'Cameroon': ['French', 'English', 'African'],
 'Canada': ['English', 'French'],
 'Cape Verde': ['Portuguese', 'Criuolo'],
 'Central African Republic': ['French', 'Sangho'],
 'Chad': ['French', 'Arabic', 'Sara'],
 'Chile': ['Spanish'],
 'China': ['Mandarin/Putonghua',
           'Yue',
           'Cantonese',
           'Wu',
           'Shanghaiese',
           'Minbei',
           'Fuzhou',
           'Minnan',
           'Hokkien-Taiwanese',
           'Xiang',
           'Gan',
           'Hakka'],
 'Colombia': ['Spanish'],
 'Comoros': ['Arabic', 'French', 'Shikomoro', 'Swahili/Arabic'],
 'Congo, Democratic Republic of the': ['French', 'Lingala', 'Monokutuba', 'Kikongo','Tshiluba'],
 'Congo, Republic of': ['French', 'Lingala', 'Monokutuba', 'Kikongo'],
 'Costa Rica': ['Spanish', 'English'],
 'Croatia': ['Croatian', 'Italian', 'Hungarian', 'Czech', 'Slovak', 'German'],
 'Cuba': ['Spanish'],
 'Cyprus': ['Greek', 'Turkish', 'English'],
 'Czech Republic': ['Czech'],
 "Côte d'Ivoire": ['French', 'Dioula'],
 'Denmark': ['Danish', 'Faroese', 'Greenlandic', 'Inuit', 'German', 'English'],
 'Djibouti': ['French', 'Arabic', 'Somali', 'Afar'],
 'Dominica': ['English', 'French'],
 'Dominican Republic': ['Spanish'],
 'East Timor': ['Tetum',
          'Portuguese',
          'Bahasa',
          'Indonesia',
          'English',
          'Tetum',
          'Galole',
          'Mambae',
          'Kemak'],
 'Ecuador': ['Spanish', 'Quechua', 'Amerindian'],
 'Egypt': ['Arabic', 'English', 'French'],
 'El Salvador': ['Spanish', 'Nahua'],
 'Equatorial Guinea': [
                'Spanish',
                'French',
                'English',
                'Fang',
                'Bubi',
                'Ibo'],
 'Eritrea Afar': ['Arabic', 'Tigre', 'Kunama', 'Tigrinya', 'Cushitic'],
 'Estonia': ['Estonian', 'Russian'],
 'Ethiopia': ['Amharic',
              'Tigrigna',
              'Orominga',
              'Guaragigna',
              'Somali',
              'Arabic',
              'English'],
 'Fiji': ['English', 'Fijian', 'Hindustani'],
 'Finland': ['Finnish', 'Swedish', 'Sami-Lapp', 'Russian'],
 'France': ['French',
            'Provençal',
            'Breton',
            'Alsatian',
            'Corsican',
            'Catalan',
            'Basque',
            'Flemish'],
 'Gabon': ['French', 'Fang', 'Myene', 'Nzebi', 'Bapounou/Eschira', 'Bandjabi'],
 'Gambia': ['English', 'Mandinka', 'Wolof', 'Fula'],
 'Georgia': ['Georgian',
             'Russian',
             'Armenian',
             'Azerbaijani',
             'Abkhaz'],
 'Germany': ['German'],
 'Ghana': ['English', 'Akan', 'Moshi-Dagomba', 'Ewe', 'Ga'],
 'Greece': ['Greek', 'English', 'French'],
 'Grenada': ['English', 'French'],
 'Guatemala': ['Spanish',
               'Quiche',
               'Cakchiquel',
               'Kekchi',
               'Mam',
               'Garifuna',
               'Xinca'],
 'Guinea': ['French', 'Malinké', 'Susu', 'Fulani'],
 'Guinea-Bissau': ['Portuguese', 'Criolo', 'African'],
 'Guyana': ['English', 'Amerindian dialects', 'Creole', 'Hindi', 'Urdu'],
 'Haiti': ['Creole', 'French'],
 'Honduras': ['Spanish', 'Amerindian dialects', 'English'],
 'Hungary Magyar': ['Hungarian'],
 'Iceland': ['Icelandic', 'English', 'Nordic', 'German'],
 'India': ['Hindi',
           'English',
           'Bengali',
           'Gujarati',
           'Kashmiri',
           'Malayalam',
           'Marathi',
           'Oriya',
           'Punjabi',
           'Tamil',
           'Telugu',
           'Urdu',
           'Kannada',
           'Assamese',
           'Sanskrit',
           'Sindhi',
           'Hindi/Urdu'],
 'Indonesia': ['Bahasa Indonesia', 'English', 'Dutch', 'Javanese', 'Balinese'],
 'Iran': ['Persian',
          'Persian',
          'Turkic',
          'Turkic',
          'Kurdish',
          'Luri',
          'Balochi',
          'Arabic',
          'Turkish'],
 'Iraq': ['Arabic', 'Kurdish', 'Kurdish', 'Assyrian', 'Armenian'],
 'Ireland': ['English', 'Irish', 'Gaelic'],
 'Israel': ['Hebrew', 'Arabic', 'English'],
 'Italy': ['Italian', 'German', 'French'],
 'Jamaica': ['English', 'Jamaican', 'Creole'],
 'Japan': ['Japanese'],
 'Jordan': ['Arabic', 'English'],
 'Kazakhstan': ['Kazak', 'Russian'],
 'Kenya': ['English', 'Swahili'],
 'Kiribati': ['English', 'I-Kiribati'],
 'Korea, North': ['Korean'],
 'Korea, South': ['Korean', 'English'],
 'Kosovo': ['Albanian', 'Serbian', 'Bosnian', 'Turkish', 'Roma'],
 'Kuwait': ['Arabic', 'English'],
 'Kyrgyzstan': ['Kyrgyz', 'Russian'],
 'Laos': ['Lao', 'French', 'English'],
 'Latvia': ['Latvian', 'Russian', 'Lithuanian'],
 'Lebanon': ['Arabic', 'French', 'English', 'Armenian'],
 'Lesotho': ['English', 'Sesotho', 'Zulu', 'Xhosa'],
 'Liberia': ['English'],
 'Libya': ['Arabic', 'Italian', 'English'],
 'Liechtenstein': ['German', 'Alemannic'],
 'Lithuania': ['Lithuanian', 'Russian', 'Polish'],
 'Luxembourg': ['Luxermbourgish', 'French', 'German'],
 'Macedonia': ['Macedonian', 'Albanian', 'Turkish', 'Roma', 'Serbian'],
 'Madagascar': ['Malagasy', 'French'],
 'Malawi': ['Chichewa',
            'Chinyanja',
            'Chiyao',
            'Chitumbuka',
            'Chisena',
            'Chilomwe',
            'Chitonga'],
 'Malaysia': ['Bahasa',
              'Melayu',
              'Malay',
              'Chinese',
              'Cantonese',
              'Mandarin',
              'Hokkien',
              'Hakka',
              'Hainan',
              'Foochow',
              'Tamil',
              'Telugu',
              'Malayalam',
              'Panjabi',
              'Thai',
              'Iban',
              'Kadazan'],
 'Maldives': ['Maldivian Dhivehi', 'English'],
 'Mali': ['French', 'Bambara'],
 'Malta': ['Maltese', 'English'],
 'Marshall Islands': [
              'Marshallese',
              'English',
              'Japanese'],
 'Mauritania': ['Hassaniya Arabic', 'Pulaar', 'Soninke', 'French', 'Wolof'],
 'Mauritius': ['English', 'Creole', 'Bojpoori', 'French'],
 'Mexico': ['Spanish', 'Mayan', 'Nahuatl'],
 'Micronesia': ['English',
                'Chukese',
                'Pohnpeian',
                'Yapase',
                'Kosrean',
                'Ulithian',
                'Woleaian',
                'Nukuoro',
                'Kapingamarangi'],
 'Moldova': ['Moldovan', 'Romanian', 'Russian', 'Gagauz'],
 'Monaco': ['French', 'English', 'Italian', 'Monégasque'],
 'Mongolia': ['Mongolian', 'Turkic', 'Russian'],
 'Montenegro': ['Serbian','Montenegrin'],
 'Morocco': ['Arabic', 'Berber', 'French'],
 'Mozambique': ['Portuguese',
                'Emakhuwa',
                'Xichangana',
                'Elomwe',
                'Cisena',
                'Echuwabo',
                'Mozambican'],
 'Myanmar': ['Burmese'],
 'Namibia': ['English', 'Afrikaans', 'German', 'Oshivambo', 'Herero', 'Nama'],
 'Nauru': ['Nauruan', 'English'],
 'Nepal': ['Nepali', 'Maithali', 'Bhojpuri', 'Tharu', 'Tamang', 'English'],
 'Netherlands': ['Dutch', 'Frisian'],
 'New Zealand': ['English', 'Maori'],
 'Nicaragua': ['Spanish', 'English'],
 'Niger': ['French', 'Hausa', 'Djerma'],
 'Nigeria': ['English', 'Hausa', 'Yoruba', 'Ibo', 'Fulani'],
 'Norway': ['Bokmål Norwegian', 'Nynorsk Norwegian', 'Sami', 'Finnish'],
 'Oman': ['Arabic', 'English', 'Baluchi', 'Urdu', 'Indian'],
 'Pakistan': ['Urdu',
              'English',
              'Punjabi',
              'Sindhi',
              'Siraiki',
              'Punjabi',
              'Pashtu',
              'Balochi',
              'Hindko',
              'Brahui',
              'Burushaski'],
 'Palau': ['Palauan',
           'English',
           'Sonsoralese',
           'Tobi',
           'Angaur',
           'Filipino',
           'Chinese',
           'Carolinian',
           'Japanese',
           'Asian'],
 'Palestinian State': ['Arabic', 'Hebrew', 'English'],
 'Panama': ['Spanish', 'English'],
 'Papua New Guinea': [
           'Tok Pisin',
           'Hiri Motu',
           'English'],
 'Paraguay': ['Spanish', 'Guaraní'],
 'Peru': ['Spanish', 'Quéchua', 'Aymara'],
 'Philippines': ['Filipino',
                 'Tagalog',
                 'English',
                 'Tagalog',
                 'Cebuano',
                 'Ilocano',
                 'Hiligaynon',
                 'Ilonggo',
                 'Bicol',
                 'Waray',
                 'Pampango',
                 'Pangasinense'],
 'Poland': ['Polish'],
 'Portugal': ['Portuguese', 'Mirandese'],
 'Qatar': ['Arabic', 'English'],
 'Romania': ['Romanian', 'Hungarian', 'German'],
 'Russia': ['Russian'],
 'Rwanda': ['Kinyarwanda', 'French', 'English', 'Kiswahili'],
 'St. Kitts and Nevis':	['English'],
 'St. Lucia': ['English' , 'French patois'],
 'St. Vincent and the Grenadines':['English', 'French patois'],
 'Samoa': ['Samoan', 'English'],
 'San Marino': ['Italian'],
 'São Tomé and Príncipe': ['Portuguese'],
 'Saudi Arabia': ['Arabic'],
 'Senegal': ['French', 'Wolof', 'Pulaar', 'Jola', 'Mandinka'],
 'Serbia': ['Serbian',
            'Romanian',
            'Hungarian',
            'Slovak',
            'Croatian',
            'Albanian'],
 'Seychelles': ['Seselwa Creole', 'English', 'French'],
 'Sierra Leone': ['English', 'Mende', 'Temne', 'Krio'],
 'Singapore': ['Mandarin',
               'English',
               'Malay',
               'Hokkien',
               'Cantonese',
               'Teochew',
               'Tamil'],
 'Slovakia': ['Slovak', 'Hungarian', 'Roma', 'Ukrainian'],
 'Slovenia': ['Slovenian', 'Serbo-Croatian'],
 'Solomon Islands': ['English', 'Melanesian'],
 'Somalia': ['Somali', 'Arabic', 'English', 'Italian'],
 'South Africa':[
                'IsiZulu',
                'IsiXhosa',
                'Afrikaans',
                'Sepedi',
                'English',
                'Setswana',
                'Sesotho',
                'Xitsonga'
 ],
 'South Sudan': [
           'English',
           'Arabic',
           'Dinka',
           'Nuer',
           'Bari',
           'Zande',
           'Shilluk'],
 'Spain': ['Spanish', 'Catalan', 'Galician', 'Basque'],
 'Sri Lanka': ['Sinhala', 'Tamil', 'English'],
 'Sudan': ['Arabic',
           'Nubian',
           'Ta Bedawie',
           'Nilotic',
           'Nilo-Hamitic',
           'Sudanic',
           'English'],
 'Suriname': ['Dutch', 'Surinamese', 'English', 'Hindustani', 'Javanese'],
 'Swaziland': ['English','Siswati'],
 'Sweden': ['Swedish', 'Sami','Finnish'],
 'Switzerland': ['German', 'French', 'Italian', 'Romansch'],
 'Syria': ['Arabic',
           'Kurdish',
           'Armenian',
           'Aramaic',
           'Circassian',
           'French',
           'English'],
 'Taiwan': ['Chinese', 'Mandarin', 'Taiwanese', 'Min', 'Hakka'],
 'Tajikistan': ['Tajik', 'Russian'],
 'Tanzania': ['Swahili', 'English', 'Arabic'],
 'Thailand': ['Thai', 'Siamese', 'English'],
 'Togo': ['French', 'Ewé', 'Mina', 'Kabyé', 'Dagomba'],
 'Tonga': ['Tongan', 'English'],
 'Trinidad and Tobago': ['English', 'Hindi', 'French', 'Spanish', 'Chinese'],
 'Tunisia': ['Arabic', 'French'],
 'Turkey': ['Turkish', 'Kurdish', 'Dimli', 'Azeri', 'Kabardian'],
 'Turkmenistan': ['Turkmen', 'Russian', 'Uzbek'],
 'Tuvalu': ['Tuvaluan', 'English', 'Samoan', 'Kiribati', 'Nui'],
 'Uganda': ['English',
            'Ganda',
            'Luganda',
            'Niger-Congo',
            'Nilo-Saharan',
            'Swahili',
            'Arabic'],
 'Ukraine': ['Ukrainian', 'Russian', 'Romanian', 'Polish', 'Hungarian'],
 'United Arab Emirates': ['Arabic','Persian','English','Hindi','Urdu'],
 'United Kingdom': ['English', 'Welsh', 'Scots Gaelic'],
 'United States': ['English', 'Spanish'],
 'Uruguay': ['Spanish', 'Portunol', 'Brazilero'],
 'Uzbekistan': ['Uzbek', 'Russian', 'Tajik'],
 'Vanuatu': ['Bislama', 'English', 'French'],
 'Vatican City': ['Italian', 'Latin', 'French'],
 'Venezuela': ['Spanish'],
 'Vietnam': ['Vietnamese',
             'English',
             'French',
             'Chinese',
             'Khmer',
             'Mon-Khmer',
             'Malayo-Polynesian'],
 'Western Sahara': ['Hassaniya Arabic', 'Moroccan Arabic'],
 'Yemen': ['Arabic'],
 'Zambia': ['English',
            'Bemba',
            'Kaonda',
            'Lozi',
            'Lunda',
            'Luvale',
            'Nyanja',
            'Tonga'],
 'Zimbabwe': ['English', 'Shona', 'Ndebele/Sindebele']}
